### ISSUE TITLE
Summary returns 1 - No Content

### ISSUE THREAD

**Issue by savionlee** [civicrm/org.civicrm.contactlayout#143] opened 2024-05-07 16:27 UTC
![image](https://github.com/civicrm/org.civicrm.contactlayout/assets/9041739/88d86f60-1cf9-46a0-a23f-f91a80bddd1f)

This unique error seems to be coming from CLE. When I disable the extension, I can see the standard blocks. I cloned the system default and put it at the top and it didn't solve the issue. 

No errors in the browser console, php error logs, or ConfigAndLog.

Tested on an Organization and Individual.

CiviCRM 5.73.1, WP 6.5.2

**Comment by colemanw** [comment] 2024-05-07 17:40
This appears to be caused by a recent upgrade to Smarty. I will investigate, but in the meantime @savionlee a quick-fix would be to comment-out the line(s) in your `civicrm.settings.php` file which contain `define('CIVICRM_SMARTY_AUTOLOAD_PATH', ...);`

**Comment by savionlee** [comment] 2024-05-07 17:59
> This appears to be caused by a recent upgrade to Smarty. I will investigate, but in the meantime @savionlee a quick-fix would be to comment-out the line(s) in your `civicrm.settings.php` file which contain `define('CIVICRM_SMARTY_AUTOLOAD_PATH', ...);`

Thanks! Disabling brought the display back.

**Comment by colemanw** [comment] 2024-05-08 23:20
Ok core PRs have been merged. This issue is now fixed.

**Closed by colemanw** 2024-05-08 23:20 UTC
