### ISSUE TITLE
Group Cascading - Show layout for parent group to contacts in a sub-group

### ISSUE THREAD

**Issue by gcpower** [civicrm/org.civicrm.contactlayout#92] opened 2021-02-07 14:41 UTC
I have built a new contact layout for a group of users.  If the contact is viewed from an event report the default contact layout is displayed.  I tested it using masquerade.  I assigned the new layout to my group.  I then switched back and I was presented with the new contact layout. I checked with a login, rather than masquerade and the result was the same.  It could be permission related, as the group has very  limited access to CiviCRM.  I am using an ACL to control access.

**Comment by colemanw** [comment] 2021-02-07 21:32
Sorry I'll need more detail to fully understand what you're saying, but a guess based on what you wrote so far is that there may be a misunderstanding about how groups work with this extension. The reason to select a group is to limit the users who are able to *view* the layout. It doesn't control the contacts who will *be viewed* with a given layout.

**Comment by gcpower** [comment] 2021-02-07 22:46
Coleman

Thank you for coming back so promptly. 

Your explanation of groups is how I understand it. I have two main groups. I built the contact summary for group called Charity admins. I checked that the person logged in was part of the group and there was data matching the selection. I allocated individuals and charity admins. The default summary was displayed. I then allocated the admin group to the summary. I logged in as an admin selecting the same person and the new contact summary was displayed. 

I hope that helps. 

Regards
Graham

**Comment by colemanw** [comment] 2021-02-07 23:21
How many layouts do you have? Remember they are selected from top to bottom. The first one the logged in user has access to will be used.

**Comment by gcpower** [comment] 2021-02-07 23:25
Coleman

I just created one. 

Graham

**Comment by gcpower** [comment] 2021-02-08 09:26
Good morning Coleman

I slept on it and took some screenshots for you.  As I was taking them I identified that the Group that the person is on is a child of the group assigned to the contact layout.  I then allocated the person to the parent group, as well.  This time the new contact layout was displayed.  Is it intended to work this way?


Regards

Graham Clarkson
gc20bc@gmail.com

**Comment by colemanw** [comment] 2021-02-08 13:37
Ok so the issue is that group cascading is not working. Users assigned to a child group do not see layouts for the parent group, unless that user is specifically assigned to the parent group.
Is that correct?

**Comment by gcpower** [comment] 2021-02-08 13:38
Coleman

Yes, that is correct. 

Regards

Graham

**Comment by colemanw** [comment] 2021-06-16 03:47
@gcpower I believe I've fixed it. Can you please review #100

**Comment by gcpower** [comment] 2021-06-29 10:07
Coleman

Sorry it has taken me a while to get to this.  I have checked it on CiviCRM 5.38.0 and Drupal 7 and it is working as expected.

Thank you.

Regards

Graham Clarkson
***@***.***

**Closed** 2021-06-29 12:52 UTC
